[package]
name = "aunt-kg"
version = "0.1.0"
edition = "2021"

[build]
rustflags = "-C opt-level=3 -C target-cpu=native -C lto=fat"

[dependencies]

[dependencies.mork]
path = "../../frontend"

[dependencies.ringmap]
path = "../../../RingMap"
features = ["all_dense_nodes"]
